# Generated by Django 5.2.15 on 2026-07-08 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doy', models.PositiveSmallIntegerField(help_text='Day Of Year, valore compreso tra 1 e 366.', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(366)])),
                ('temperature', models.FloatField(help_text='Temperatura media giornaliera in gradi Celsius.')),
                ('bagnatura', models.PositiveSmallIntegerField(help_text='Bagnatura fogliare media giornaliera: 0=asciutta, 1=bagnata.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('humidity', models.FloatField(help_text='Umidità media giornaliera percentuale, valore compreso tra 0 e 100.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('rain', models.FloatField(help_text='Pioggia cumulata giornaliera in millimetri.', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('events', models.JSONField(blank=True, default=list, help_text='Stato finale degli eventi alla fine del giorno.')),
                ('processed', models.BooleanField(default=False, help_text='Indica se il giorno è già stato processato dal modello.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'forecast day',
                'verbose_name_plural': 'forecast days',
                'ordering': ['doy'],
                'constraints': [models.CheckConstraint(condition=models.Q(('doy__gte', 1), ('doy__lte', 366)), name='forecastday_doy_between_1_and_366'), models.CheckConstraint(condition=models.Q(('bagnatura__gte', 0), ('bagnatura__lte', 1)), name='forecastday_bagnatura_between_0_and_1'), models.CheckConstraint(condition=models.Q(('humidity__gte', 0.0), ('humidity__lte', 100.0)), name='forecastday_humidity_between_0_and_100'), models.CheckConstraint(condition=models.Q(('rain__gte', 0.0)), name='forecastday_rain_gte_0')],
            },
        ),
    ]
